// <auto-generated />
using System;
using Checkpoint01.AspNet.CoreMVC.Ambers.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Checkpoint01.AspNet.CoreMVC.Ambers.Migrations
{
    [DbContext(typeof(IChurrosContext))]
    partial class IChurrosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Checkpoint01.AspNet.CoreMVC.Ambers.Models.Churros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CoberturaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDeAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("RecheioId")
                        .HasColumnType("int");

                    b.Property<int>("Tamanho")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoberturaId");

                    b.HasIndex("RecheioId");

                    b.ToTable("Tbl_Churros");
                });

            modelBuilder.Entity("Checkpoint01.AspNet.CoreMVC.Ambers.Models.ChurrosPedido", b =>
                {
                    b.Property<int>("ChurrosId")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.HasKey("ChurrosId", "PedidoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Tbl_Churros_Pedido");
                });

            modelBuilder.Entity("Checkpoint01.AspNet.CoreMVC.Ambers.Models.Cobertura", b =>
                {
                    b.Property<int>("CoberturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Descricao");

                    b.HasKey("CoberturaId");

                    b.ToTable("Tbl_Cobertura");
                });

            modelBuilder.Entity("Checkpoint01.AspNet.CoreMVC.Ambers.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Nascimento");

                    b.HasKey("PedidoId");

                    b.ToTable("Tbl_Pedido");
                });

            modelBuilder.Entity("Checkpoint01.AspNet.CoreMVC.Ambers.Models.Recheio", b =>
                {
                    b.Property<int>("RecheioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RecheioId");

                    b.ToTable("Tbl_Recheio");
                });

            modelBuilder.Entity("Checkpoint01.AspNet.CoreMVC.Ambers.Models.Churros", b =>
                {
                    b.HasOne("Checkpoint01.AspNet.CoreMVC.Ambers.Models.Cobertura", "Cobertura")
                        .WithMany()
                        .HasForeignKey("CoberturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Checkpoint01.AspNet.CoreMVC.Ambers.Models.Recheio", "Recheio")
                        .WithMany("Churros")
                        .HasForeignKey("RecheioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cobertura");

                    b.Navigation("Recheio");
                });

            modelBuilder.Entity("Checkpoint01.AspNet.CoreMVC.Ambers.Models.ChurrosPedido", b =>
                {
                    b.HasOne("Checkpoint01.AspNet.CoreMVC.Ambers.Models.Churros", "Churros")
                        .WithMany("ChurrosPedidos")
                        .HasForeignKey("ChurrosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Checkpoint01.AspNet.CoreMVC.Ambers.Models.Pedido", "Pedido")
                        .WithMany("ChurrosPedidos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Churros");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Checkpoint01.AspNet.CoreMVC.Ambers.Models.Churros", b =>
                {
                    b.Navigation("ChurrosPedidos");
                });

            modelBuilder.Entity("Checkpoint01.AspNet.CoreMVC.Ambers.Models.Pedido", b =>
                {
                    b.Navigation("ChurrosPedidos");
                });

            modelBuilder.Entity("Checkpoint01.AspNet.CoreMVC.Ambers.Models.Recheio", b =>
                {
                    b.Navigation("Churros");
                });
#pragma warning restore 612, 618
        }
    }
}
